---
- name: Install miniDNLA
  apt: name=minidlna state=present

- name: Copy miniDLNA configuration in place.
  template:
    src: minidlna.conf.j2
    dest: /etc/minidlna.conf
    owner: root
    group: root
    mode: 0644
#  notify:
#    - reload minidlna

- name: Ensure miniDLNA is started and enabled to start at boot.
  service: name=minidlna state=started enabled=yes